baseurl = "https://notes.wadeism.net/"
title = "Nothing but.."
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "notes-wadeism"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-120924943-1"
preserveTaxonomyNames = true
paginate = 20 #frontpage pagination

hasCJKLanguage = true
summaryLength = 20

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service 
    disable = false
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Something here"
  description = "My notes for everyone" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "wade"
  authorLink = "https://notes.wadeism.net/"
  bio = [
    "本站站長"
  ]
  copyright = [
    "&copy; 2022 Wade",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "A port of Tracks by Compete Themes."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "wade0702@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  #name = "Get in touch"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  # facebook      = "full Social profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  # email         = "email@example.com"
  # twitter       = "full profile url in twitter"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "full profile url in instagram"
  #github        = "full profile url in github"
  github        = "https://github.com/wade-chiang"
  # pinterest     = "full profile url in pinterest"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."wade"]
    link = "https://notes.wadeism.net"
    email = "wade0702@gmail.com"
    bio = [
      "自稱台主"
    ]
    facebook      = "full lukas profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    # twitter       = "full profile url in twitter"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    github        = "full profile url in github"
    # pinterest     = "full profile url in pinterest"

    # [params.writers."Göran Svensson"]
    # link = "https://appernetic.io/"
    # email = "goran@molnsys.com"
    # bio = [
    #   "Göran is an avid blogger and the founder of <a href='https://appernetic.io/'>Appernetic.io</a>. This is the author bio shown after posts."
    # ]
    # facebook      = "full Göran profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    # twitter       = "full profile url in twitter"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    # github        = "full profile url in github"
    # pinterest     = "full profile url in pinterest"


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
